package com.alipay.antchain.bridge.plugins.dioxide.gcl;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.util.Base64;

public class GclCodegen {

    /**
     * offchain-plugin 与 onchain-plugin 同级
     */
    private static final Path ONCHAIN_ROOT =
            Paths.get("..", "onchain-plugin").normalize();

    /**
     * 生成到当前 package 目录
     */
    private static final Path OUTPUT_DIR =
            Paths.get("src", "main", "java",
                    "com", "alipay", "antchain", "bridge",
                    "plugins", "dioxide", "gcl");

    private static final String PKG =
            "com.alipay.antchain.bridge.plugins.dioxide.gcl";

    public static void main(String[] args) throws Exception {
        if (!Files.exists(ONCHAIN_ROOT)) {
            throw new IllegalStateException(
                    "onchain-plugin not found: " + ONCHAIN_ROOT.toAbsolutePath());
        }

        generateContracts();
        generateDir("Interfaces", ONCHAIN_ROOT.resolve("interfaces"));
        generateDir("Libs", ONCHAIN_ROOT.resolve("lib"));
    }

    /**
     * onchain-plugin/*.gcl → Contracts.java
     */
    private static void generateContracts() throws IOException {
        StringBuilder body = new StringBuilder();

        try (DirectoryStream<Path> stream =
                     Files.newDirectoryStream(ONCHAIN_ROOT, "*.gcl")) {

            for (Path p : stream) {
                appendField(body, p);
            }
        }

        writeJava("Contracts", body);
    }

    /**
     * 子目录（interfaces / lib）
     */
    private static void generateDir(String className, Path dir) throws IOException {
        if (!Files.exists(dir)) {
            return;
        }

        StringBuilder body = new StringBuilder();

        Files.walk(dir)
                .filter(Files::isRegularFile)
                .filter(p -> p.toString().endsWith(".gcl"))
                .forEach(p -> {
                    try {
                        appendField(body, p);
                    } catch (IOException e) {
                        throw new RuntimeException(e);
                    }
                });

        writeJava(className, body);
    }

    private static void appendField(StringBuilder sb, Path file) throws IOException {
        String base64 = Base64.getEncoder()
                .encodeToString(Files.readAllBytes(file));

        String constName = file.getFileName()
                .toString()
                .replace(".gcl", "")
                .replaceAll("[^a-zA-Z0-9]", "_")
                .toUpperCase();

        sb.append("    /** source: ")
                .append(file.toString().replace("\\", "/"))
                .append(" */\n");

        sb.append("    public static final String ")
                .append(constName)
                .append(" = \"")
                .append(base64)
                .append("\";\n\n");
    }

    private static void writeJava(String className, StringBuilder body) throws IOException {
        Files.createDirectories(OUTPUT_DIR);

        Path javaFile = OUTPUT_DIR.resolve(className + ".java");

        String code =
                "package " + PKG + ";\n\n" +
                        "/**\n" +
                        " * AUTO-GENERATED BY GclCodegen\n" +
                        " * DO NOT EDIT MANUALLY\n" +
                        " */\n" +
                        "public final class " + className + " {\n\n" +
                        body +
                        "}\n";

        Files.writeString(javaFile, code, StandardCharsets.UTF_8);
    }
}
